---
ID: "1f5b12b5-b30e-4789-a550-0d2ba7efefe0"
Parent: "7a92c2b0-94cb-47f9-8c6e-39065a4edbd9"
Template: "4b2ff096-08b8-41b8-8ac1-597329d3d5dc"
Path: /sitecore/content/Global Repository/Vacancies/Product Owner
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1e6e4fc6-95c8-458f-a233-b8c9b9c328d4"
      Hint: Text
      Value: "Are you our new Product Owner?"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211018T180844Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "707b65c7-027b-4fc1-aad6-32c64eaa727c"
    - ID: "92b53f13-954a-4d6c-a1ba-22a26fda0de3"
      Hint: Title
      Value: Product Owner
    - ID: "9f6aa4f3-c392-4ca6-9957-b26aa40da93f"
      Hint: FriendlyUrl
      Value: "product-owner"
    - ID: "ac47ffec-343e-40d8-81fd-fc65bb5929f6"
      Hint: Related Employer
      Value: "{CCBDD59B-C75C-4149-BCB0-CF010C320027}"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211019T173142Z
